installCRDs: true

serviceAccount:
  name: external-secrets-operator
  create: false

logLevel: warn

nodeSelector: { "karpenter.sh/nodepool": "system" }

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"

certController:
  nodeSelector: { "karpenter.sh/nodepool": "system" }

  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"

webhook:
  nodeSelector: { "karpenter.sh/nodepool": "system" }

  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
